# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 788ab997ad2ba61dbd43fdc3c8550c91514f6973a9313c46504ff957fc5d59e721e8b7fe6ad43ea7074237e91c7fc089c8a6a87070fbabc7cc4bd8f093994093

test:
  secret_key_base: 7804c35bb0b9f6f9f47150c4d96f866fe3c0c7b06fb2497dda8ca487bedd97decd8097bc8c2561f6bdec2f5cedc85ac5a81b9a106cae717b7ec3910196dc011b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
